
title = "给世界一点极好的信息"

total = 7

text1 = "如何给人类真正做点好事？你有什么建议吗？"
text2 = "怎样真正帮助人、帮助更多人？你有什么建议吗？"
text3 = "就在今天，我的生命将是一场欢庆！"
text4 = "多喝点水，站起来走走吧！"
text5 = "学习别人，相信自己，寻找自己的感觉，要相信直觉！"
text6 = "最重要的事，只有一件，找出当下最重要的一件事，去做，成功！"
text7 = "站起来走走，晒晒太阳，吹吹风，呼吸呼吸新鲜空气，感受感受大自然！”
