
title = "给世界一点极好的信息"

total = 7

# 海格尔说：凡是现实都是合理的，凡是合理的都是现实的。（All than is real is rational; and all that is rational is real.)
# 吃饭时候，不看手机
# 柳永《雨霖铃》：“此去经年，应是良辰好景虚设。 便纵有千种风情，更与何人说？”
# Aristotle（亚里士多德），希腊著名的哲学家和科学家，曾经说过：“对于那些我们在能做到之前必须学习如何做的事情，我们需要边做边学 (For the things we have to learn before we can do them, we learn by doing them.)”。

text1 = "如何给人类真正做点好事？你有什么建议吗？"
text2 = "怎样真正帮助人、帮助更多人？你有什么建议吗？"
text3 = "就在今天，我的生命将是一场欢庆！"
text4 = "多喝点水，站起来走走吧！"
text5 = "学习别人，相信自己，寻找自己的感觉，要相信直觉！"
text6 = "最重要的事，只有一件，找出当下最重要的一件事，去做，成功！"
text7 = "站起来走走，晒晒太阳，吹吹风，呼吸呼吸新鲜空气，感受感受大自然！"
text8 = "新生代，寻城记"
text9 = "不要着急，休息，休息，休息一会，一休哥"

# 注释信息
[day_time_1]
total = 7
text1 = "如何给人类真正做点好事？你有什么建议吗？"
text2 = "怎样真正帮助人、帮助更多人？你有什么建议吗？"
text3 = "就在今天，我的生命将是一场欢庆！"
text4 = "多喝点水，站起来走走吧！"
text5 = "学习别人，相信自己，寻找自己的感觉，要相信直觉！"
text6 = "最重要的事，只有一件，找出当下最重要的一件事，去做，成功！"
text7 = "站起来走走，晒晒太阳，吹吹风，呼吸呼吸新鲜空气，感受感受大自然！"

# 注释信息
[day_time_2]
total = 2
text1 = "如何给人类真正做点好事？你有什么建议吗？"
text2 = "怎样真正帮助人、帮助更多人？你有什么建议吗？"

# 注释信息
[day_time_3]
total = 2
text1 = "如何给人类真正做点好事？你有什么建议吗？"
text2 = "怎样真正帮助人、帮助更多人？你有什么建议吗？"

# 注释信息
[day_time_4]
total = 2
text1 = "如何给人类真正做点好事？你有什么建议吗？"
text2 = "怎样真正帮助人、帮助更多人？你有什么建议吗？"

# 注释信息
[day_time_5]
total = 2
text1 = "如何给人类真正做点好事？你有什么建议吗？"
text2 = "怎样真正帮助人、帮助更多人？你有什么建议吗？"

# 注释信息
[day_time_6]
total = 2
text1 = "如何给人类真正做点好事？你有什么建议吗？"
text2 = "怎样真正帮助人、帮助更多人？你有什么建议吗？"

# 注释信息
[day_time_7]
total = 2
text1 = "如何给人类真正做点好事？你有什么建议吗？"
text2 = "怎样真正帮助人、帮助更多人？你有什么建议吗？"

# 注释信息
[day_time_8]
total = 2
text1 = "如何给人类真正做点好事？你有什么建议吗？"
text2 = "怎样真正帮助人、帮助更多人？你有什么建议吗？"

# 注释信息
[day_time_9]
total = 2
text1 = "如何给人类真正做点好事？你有什么建议吗？"
text2 = "怎样真正帮助人、帮助更多人？你有什么建议吗？"

# 注释信息
[day_time_10]
total = 2
text1 = "如何给人类真正做点好事？你有什么建议吗？"
text2 = "怎样真正帮助人、帮助更多人？你有什么建议吗？"
